development:
  adapter: postgresql
  encoding: unicode
  database: ericandasmita_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: ericandasmita_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: ericandasmita
  pool: 5
  username: admin
  password: password1
