development:
  adapter: postgresql
  encoding: unicode
  database: ericandasmita_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: ericandasmita_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['db_name'] %>
  host: ec2-54-83-61-45.compute-1.amazonaws.com
  pool: 5
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>
